import { useNavigate } from 'react-router';

export function SAGView() {
  const navigate = useNavigate();

  return (
    <div className="p-6">
      <div className="text-sm text-[#666] mb-4">
        Training Projects › Shielded Metal Arc Welding NC II › CATS Development › SAG
      </div>

      <h1 className="text-xl font-semibold text-[#333] mb-1">
        <span className="inline-block px-2.5 py-0.5 rounded text-[11px] font-bold tracking-wide bg-[#FFF3E0] text-[#E65100] mr-2">
          PHASE 3
        </span>
        Self-Assessment Guide (SAG)
      </h1>
      <p className="text-sm text-[#666] mb-6">
        Evidence Plan without assessment methods — Locked until Phase 3
      </p>

      <div className="bg-white border border-[#E0E0E0] rounded opacity-60 pointer-events-none p-6">
        <p className="text-sm text-[#666] mb-4 text-center">
          Generated by removing assessment method columns from Evidence Plan and adding YES/NO checkboxes
        </p>
        <div className="bg-[#F5F5F5] rounded p-4">
          <div className="text-xs font-semibold text-[#999] uppercase mb-2">Sample Format:</div>
          <div className="border border-[#E0E0E0] rounded bg-white p-3 space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm">Identify type and size of electrode *</span>
              <div className="flex gap-4">
                <label className="flex items-center gap-2 text-sm"><input type="checkbox" /> YES</label>
                <label className="flex items-center gap-2 text-sm"><input type="checkbox" /> NO</label>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-sm">Set up welding machine and accessories</span>
              <div className="flex gap-4">
                <label className="flex items-center gap-2 text-sm"><input type="checkbox" /> YES</label>
                <label className="flex items-center gap-2 text-sm"><input type="checkbox" /> NO</label>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="mt-6 flex justify-end">
        <button
          onClick={() => navigate('/')}
          className="px-4 py-2 bg-white text-[#666] border border-[#E0E0E0] rounded text-sm font-medium hover:bg-[#F5F5F5]"
        >
          ← Back to Dashboard
        </button>
      </div>
    </div>
  );
}
